---
- name: Update system
  apt: update_cache=yes

- name: Install components
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - prometheus
    - apt-transport-https
    - software-properties-common
    - wget
    - prometheus-alertmanager

- name: Add key grafana
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install components
  apt:
    name: grafana

#- name: Add rules.yml
#  template:
#    src=templates/rules.yml
#    dest=/etc/prometheus/rules.yml
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: templates/rules.yml
    dest: /etc/prometheus/rules.yml
    mode: '0644'

- name: Add Prometheus config prometheus.yml
  template:
    src=templates/prometheus.yml
    dest=/etc/prometheus/prometheus.yml
  notify:
    - grafana-start
    - prometheus
    - prometheus-alertmanager
