groups:
  - name: node exporter
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Service node_exporter in server {{ $labels.instance }} not active"
          description: "Server node_exporter its down \n
VALUE = {{ $value }}\n LABELS = {{ $labels }}"
