---
- name: Update system
  apt: update_cache=yes

- name: Install mysql
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mysql-server
    - python-pymysql
    - python3-pymysql
    - python-apt
    - python3-apt

- name: Add MySQL config mysql.cnf
  template:
    src=templates/mysqld.cnf
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf

- name: Reload mysql
  service: name=mysql.service state=restarted

- name: Create user wordpass
  command: 'mysql -ne "{{ item }}"'
  with_items:
    -  CREATE USER 'repl'@'192.168.10.103' IDENTIFIED BY 'secret';
    -  GRANT REPLICATION SLAVE ON *.* TO 'repl'@'192.168.10.103';
  changed_when: False
  ignore_errors: yes

- name: Save FILE and POS
  command: 'mysql -ne "{{ item }}"'
  with_items:
    -  SHOW MASTER STATUS \G;
  register: command_output

- debug: var=command_output

- name: Set password for root user
  mysql_user:
    name: "root"
    password: "secret"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Add config .my.cnf
  template:
    src=templates/.my.cnf
    dest=/root/.my.cnf

- name: Mysql - Check master replication status.
  mysql_replication: mode=getprimary
  register: master

- name: 123
  add_host:
    name:   "master_value_holder"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"

- name: Reload mysql
  service: name=mysql.service state=restarted
